### ISSUE TITLE
I am unable to install in Kali

### ISSUE THREAD

**Issue by frafrichile** [vk496/linset#5]
what are the steps to install this tool in Kali ?

**Comment by ghost** [comment]
Download the ZIP and place linset on your desktop.
Open a terminal and write the following commands:

> > cd Desktop
> > bash linset

If you require administrative privileges, add 'sudo' to the start of the previous command.
Be sure to install any other additional packages if indicated in linset.

**Comment by frafrichile** [comment]
Thanks that worked.
